### PR TITLE
Update colour palette and fonts

### PR DESCRIPTION
**Pull request by dimitraz**
## Description 
* Consistent margin and padding for all elements
* Update line height and margins in nav bar 
* Change colour palette (black and slightly transparent for content, nav bar and footer)
* Update title fonts to use Archivo Black

## Screenshots
Screenshot 2020-11-05 at 13 52 54
Screenshot 2020-11-05 at 13 53 01

### CODE REVIEW

**Comment by dimitraz** [comment]
Hi guys @marcotroisi @alezucca please note a short period of maintenance mode will be required before this is merged/pushed for manual tweaks within the wordpress editor (for widget content, home page content and background) 

Also working on a better quality custom background

**Comment by alezucca** [comment]
Yes looks great!

**Review by marcotroisi — APPROVED** [review]
Looks awesome!

**Comment by marcotroisi** [comment]
@dimitraz I think this might be the plugin we used to use: https://wppusher.com/

**Pull request merged**
